CFG:
  # Decoding strategy
  decoding_strategy: "greedy"  # Options: "greedy", "beam_search", "top_k_sampling", "top_p_sampling", "decaying_temperature"

  # Common parameters
  max_prefix_length: 20
  generate_token_length: 300
  repetition_penalty: 1.3
  no_repeat_ngram_size: 3
  num_return_sequences: 1

  # Beam search parameters (used if decoding_strategy is "beam_search")
  num_beams: 5

  # Top-k sampling parameters (used if decoding_strategy is "top_k_sampling")
  top_k: 40

  # Top-p sampling parameters (used if decoding_strategy is "top_p_sampling")
  top_p: 0.9

  # Temperature settings
  temperature: 0.5  # Standard temperature for sampling strategies
  initial_temperature: 10.0  # Initial temperature for decaying temperature strategy

  # Inference batch size
  inference_batch_size: 1

  # Other parameters
  seed: 42
  inference_result_file_name: "/Generated/Results"    #Output will be Result.csv
